import test from 'node:test';
import assert from 'node:assert/strict';
import {Journey} from '../public/dont-look/engine.js';
import {readSave,WORLDS} from '../public/dont-look/worlds.js';
function tick(game,n){for(let i=0;i<n;i++)game.update(1/60);}
test('Gaze changes UFO behaviour and catches it; ignorance lets it approach',()=>{const j=new Journey();j.start(0);const a=j.actors[0],before=Math.hypot(a.x-j.hero.x,a.y-j.hero.y);j.look(0,0);tick(j,60);assert.ok(Math.hypot(a.x-j.hero.x,a.y-j.hero.y)<before);j.look(a.x,a.y);const x=a.x;tick(j,30);assert.equal(a.x,x);tick(j,50);assert.equal(j.done,1);});
test('Whole campaign can be completed by gaze alone, including belly escape and finale',()=>{for(let level=0;level<WORLDS.length;level++){const j=new Journey();j.start(level,level);for(let n=0;n<60*120&&['playing','landing'].includes(j.state);n++){const actors=j.actors.filter(a=>!a.rewarded&&a.react<=0),eye=actors.find(a=>a.kind==='eye');let target=actors.find(a=>['target','objective'].includes(a.role));if(eye){target=j.timer%6>=2.65?eye:actors.find(a=>a.kind==='ufo');}if(target)j.look(target.x,target.y);else j.look(0,0);j.update(1/60);}assert.equal(j.state,'won',`world ${level+1}`);assert.ok(j.hp>0);}});
test('Pause, resize and retry preserve safe checkpoints',()=>{const j=new Journey();j.start(2,3);tick(j,90);const time=j.timer;j.state='paused';tick(j,600);assert.equal(j.timer,time);j.resize(700,1300);assert.ok(j.actors.every(a=>Number.isFinite(a.x)&&Number.isFinite(a.y)));j.start(2,3);assert.equal(j.hp,100);assert.equal(j.done,0);assert.equal(j.unlocked,3);});
test('Heals, shields and powers work without bypassing unlocks or cooldowns',()=>{const j=new Journey();j.start(1,1);assert.equal(j.power('nova'),false);j.hit(50);const juice=j.actors.find(a=>a.kind==='juice');j.look(juice.x,juice.y);tick(j,85);assert.equal(j.hp,85);assert.equal(j.power('blink'),true);assert.equal(j.power('blink'),false);j.hit(90);assert.equal(j.hp,85);tick(j,190);j.hit(90);assert.equal(j.state,'lost');});
test('Close enemies remain catchable and Super Stare removes threats',()=>{const j=new Journey();j.start(2,6);const a=j.actors[0];a.x=j.hero.x+60;a.y=j.hero.y;j.look(a.x,a.y);tick(j,130);assert.equal(j.done,1);assert.equal(j.hp,100);j.start(6,6);const threat=j.actors.find(a=>a.role==='threat');assert.ok(threat);j.power('nova');assert.ok(threat.rewarded);tick(j,100);assert.ok(!j.actors.includes(threat));});
test('Eaten sequence remains survivable even when arriving on low health',()=>{const j=new Journey();j.start(4,4);j.hp=1;tick(j,150);assert.equal(j.state,'playing');assert.equal(j.swallowed,true);assert.ok(j.hp>0);assert.equal(j.actors.length,3);});
test('Malformed and unavailable saves recover safely; unlocks are bounded',()=>{assert.equal(readSave({getItem:()=>'{oops'}).unlocked,0);assert.equal(readSave({getItem:()=>{throw Error();}}).unlocked,0);const save=readSave({getItem:()=>JSON.stringify({version:1,unlocked:999,best:[-10,'abc',200],sound:true})});assert.equal(save.unlocked,8);assert.deepEqual(save.best.slice(0,3),[0,0,200]);});
