import test from 'node:test';import assert from 'node:assert/strict';
import {Adventure} from '../public/roland-home/physics.js';
import {fresh,normalizeSave,mergeSaves,PLANETS,SYSTEMS,GEAR,savedStage,experience,characterStats} from '../public/roland-home/data.js';
import {restoreStage} from '../public/roland-home/expedition.js';
export function pilot(a,max=28000){
 let wasStuck=0,lastX=a.hero.x;
 for(let i=0;i<max&&a.state==='playing';i++){
  if(a.vehicle&&!a.vehicle.mounted&&Math.abs(a.hero.x-a.vehicle.x)<135)a.interact();
  const b=a.boss;
  let item=a.items.filter(x=>!x.got&&!x.bossLocked&&['part','gear','signal'].includes(x.kind)).sort((x,y)=>x.x-y.x)[0];
  let x=item?.x??a.length,y=item?.y??a.floor-130;
  if(b?.active&&!b.dead){x=b.phase==='warning'?b.targetX+(b.targetX>b.x-250?-220:220):b.x-240;x=Math.max(a.length-870,Math.min(a.length-200,x));y=a.floor-90;}
  a.setTarget(x,y);a.keys.boost=!['ship','fly','swim'].includes(a.mode())&&Math.abs(x-a.hero.x)>130;
  if(a.mode()==='bounce'&&item&&Math.abs(x-a.hero.x)<150&&item.y<a.hero.y-38)a.keys.boost=true;
  if(a.mode()==='walk'&&!a.activeField&&Math.abs(x-a.hero.x)>25)a.keys.boost=true;
  a.update(1/60);
  if(i%600===599){if(Math.abs(a.hero.x-lastX)<60)wasStuck++;else wasStuck=0;lastX=a.hero.x;if(wasStuck>=3)break;}
 }
 return a;
}
test('Open galaxy has 36 unique worlds and five full-length sectors per safe world',()=>{assert.equal(SYSTEMS.length,13);assert.equal(Object.keys(PLANETS).length,36);assert.ok(SYSTEMS.every(s=>!s.level));for(const [id,p]of Object.entries(PLANETS)){if(p.fatal)continue;const a=new Adventure();a.start(id);assert.ok(a.length>=16250);assert.equal(a.stages.length,5);assert.ok(a.terrain.length>60);for(let n=0;n<5;n++){assert.ok(a.items.some(i=>i.x>=n*a.stageLength&&i.x<(n+1)*a.stageLength));assert.ok(a.enemies.some(i=>i.baseX>=n*a.stageLength&&i.baseX<(n+1)*a.stageLength));}}});
test('Saved stage claims merge monotonically and old accounts retain their discoveries',()=>{const old=normalizeSave({version:1,parts:['engine'],completed:['moo'],discovered:['udder']});assert.equal(experience(old),150);assert.equal(savedStage(old,'ocean'),0);const next=normalizeSave({...old,claims:[...old.claims,'stage:ocean:3','stage:ocean:99','stage:angler:4','foe:ocean:24','shard:ocean:29','cache:ocean:4','signal:ocean:2']});assert.equal(savedStage(next,'ocean'),3);assert.equal(next.claims.includes('stage:ocean:99'),false);assert.equal(next.claims.includes('stage:angler:4'),false);assert.equal(savedStage(mergeSaves(next,old),'ocean'),3);assert.deepEqual(normalizeSave(next),next);const a=new Adventure();a.start('ocean',[],next);assert.equal(a.stage,3);assert.ok(a.platformAt(a.hero.x));assert.equal(a.hero.hp,a.hero.maxHp);});
test('All worlds support a complete expedition, all part pickups and exclusive equipment',()=>{const failures=[];for(const [id,p]of Object.entries(PLANETS)){if(p.fatal)continue;const a=new Adventure();a.start(id);pilot(a);if(a.state!=='complete'||!a.hasPart||a.items.some(i=>i.kind==='gear'&&!i.got))failures.push({id,state:a.state,x:Math.round(a.hero.x),hp:a.hero.hp,part:a.hasPart,mode:a.mode(),missing:a.items.filter(i=>!i.got&&['part','gear','signal'].includes(i.kind)).map(i=>i.id)});}assert.deepEqual(failures,[]);});
test('Tap targets do not drift with the camera; gravity fields disable bounce',()=>{const a=new Adventure();a.start('moo');a.setTarget(650,a.floor-70);for(let n=0;n<300;n++)a.update(1/60);assert.ok(Math.abs(a.hero.x-650)<15);assert.equal(a.target,null);restoreStage(a,0);a.hero.x=a.fields[0].x+80;a.hero.y=a.floor-a.hero.r;a.keys.boost=true;for(let n=0;n<120;n++)a.update(1/60);assert.equal(a.mode(),'walk');assert.ok(Math.abs(a.hero.y-(a.floor-a.hero.r))<1);assert.equal(a.hero.vy,0);});
test('Timed barriers hold a route until open, and checkpoint replay never spends saved progress',()=>{const a=new Adventure();a.start('hollow');const gate=a.gates[0];a.hero.x=gate.x-90;a.hero.y=a.floor-a.hero.r;a.timer=gate.period-gate.offset+.1;a.setTarget(gate.x+150,a.floor-50);for(let i=0;i<60;i++)a.update(1/60);assert.ok(a.hero.x<=gate.x-a.hero.r+.01);for(let i=0;i<360;i++)a.update(1/60);assert.ok(a.hero.x>gate.x+gate.w);});
test('Live suit swaps cannot heal, reset bosses, or refill the one-time Chrono rescue',()=>{const a=new Adventure();const s=normalizeSave({...fresh(),gear:['starter','crystal','chrono','jet'],claims:['gear:prism','gear:clock','gear:aerie']});a.start('quartz',[],s);a.retryArena();a.hero.hp=44;a.rewound=true;const x=a.hero.x,boss=a.boss;s.equipped.suit='crystal';a.equip(s);assert.equal(a.hero.hp,44);assert.equal(a.hero.x,x);assert.equal(a.boss,boss);s.equipped.suit='chrono';a.equip(s);assert.ok(a.hero.hp<=44);assert.equal(a.rewound,true);s.equipped.relic='jet';a.equip(s);assert.equal(a.mode(),'fly');assert.equal(a.stats.maxHp,characterStats(s).maxHp);assert.equal(GEAR.crystal.source,'prism');});
test('Maximum legitimate save fits the account request cap',()=>{const s=fresh();for(const [id,p]of Object.entries(PLANETS)){if(p.fatal)continue;s.completed.push(id);for(let n=0;n<25;n++)s.claims.push('foe:'+id+':'+n);for(let n=0;n<30;n++)s.claims.push('shard:'+id+':'+n);for(let n=1;n<5;n++)s.claims.push('stage:'+id+':'+n);for(let n=0;n<5;n++)s.claims.push('cache:'+id+':'+n);for(let n=0;n<3;n++)s.claims.push('signal:'+id+':'+n);if(p.gear){s.claims.push('gear:'+id);s.gear.push(p.gear);}if(p.boss)s.claims.push('boss:'+id);}const normalized=normalizeSave(s);assert.ok(Buffer.byteLength(JSON.stringify({save:normalized,revision:1}))<128000);assert.equal(normalized.claims.length,s.claims.length+s.completed.length);assert.deepEqual(mergeSaves(normalized,normalized),normalized);});
test('Flight and swimming support keyboard descent and mobile targets stay below the header',()=>{for(const id of ['aerie','ocean']){const a=new Adventure();a.start(id);a.keys.boost=true;for(let n=0;n<40;n++)a.update(1/60);const high=a.hero.y;a.keys.boost=false;a.keys.down=true;for(let n=0;n<55;n++)a.update(1/60);assert.ok(a.hero.y>high+40);a.resize(680,1400);a.setTarget(500,10);assert.equal(a.target.y,330);}});
test('Tiny cave caches require the shrink potion; equipment and stage health do not refill on replay',()=>{const a=new Adventure();a.start('hollow');const cache=a.items.find(i=>i.kind==='cache'&&i.requires==='shrink');a.hero.x=cache.x;a.hero.y=cache.y;a.update(1/180);assert.equal(cache.got,false);a.potion('shrink');a.hero.y=cache.y;a.update(1/180);assert.equal(cache.got,true);const e=new Adventure();e.start('moo');let events=0;e.emit=type=>{if(type==='stage')events++;};e.hero.hp=30;e.hero.x=e.stageLength+90;e.update(1/180);assert.equal(events,1);const hp=e.hero.hp;e.hero.x=e.stageLength-90;e.update(1/180);e.hero.x=e.stageLength+90;e.update(1/180);assert.equal(events,1);assert.equal(e.hero.hp,hp);});
