"use client";

import {useEffect,useState} from 'react';
import Link from 'next/link';
import styles from './GameAdmin.module.css';

type Access={signedIn:boolean;admin:boolean;setupAvailable:boolean};
type Report={generatedAt:number;trackingSince:number|null;days:number;active:number;windows:{days:number;players:number}[];activeMinutes:number;attempts:number;completions:number;planets:{planet:string;name:string;starts:number;completions:number;deaths:number;exits:number}[];stages:{planet:string;stage:number;name:string;stageName:string;plays:number;players:number}[];feedback:{name:string;rating:number;reason:string;votes:number}[];trend:{day:number;players:number;minutes:number}[];errors:{name:string;value:string;reports:number}[];insights:{tone:string;title:string;text:string}[];definitions:Record<string,string>};
async function api(action:string,options:RequestInit={}){const r=await fetch('/api/roland/'+action,{cache:'no-store',credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.error||'The dashboard is temporarily unavailable.'),{status:r.status});return data;}
const number=(value:number)=>new Intl.NumberFormat('en-ZA').format(value);
export function GameAdmin(){
 const [access,setAccess]=useState<Access|null>(null),[report,setReport]=useState<Report|null>(null),[days,setDays]=useState(7),[error,setError]=useState(''),[busy,setBusy]=useState(false),[register,setRegister]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let alive=true;api('admin-access').then(data=>{if(alive)setAccess(data);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[refresh]);
 useEffect(()=>{if(!access?.admin)return;const controller=new AbortController();async function load(){try{const data=await api('admin-insights?days='+days,{signal:controller.signal});setReport(data);setError('');}catch(e){if(controller.signal.aborted)return;const problem=e as Error&{status?:number};setError(problem.message);if(problem.status===403||problem.status===401){setReport(null);setAccess({signedIn:false,admin:false,setupAvailable:false});}}}load();const timer=setInterval(()=>{if(!document.hidden)load();},60000);return()=>{controller.abort();clearInterval(timer);};},[access?.admin,days,refresh]);
 async function authenticate(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);try{await api(register?'register':'login',{method:'POST',body:JSON.stringify({email:form.get('email'),password:form.get('password')})});setAccess(await api('admin-access'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function claim(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);try{await api('admin-claim',{method:'POST',body:JSON.stringify({token:form.get('token')})});event.currentTarget?.reset();setAccess(await api('admin-access'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){try{await api('logout',{method:'POST',body:'{}'});setReport(null);setAccess(await api('admin-access'));}catch(e){setError((e as Error).message);}}
 const maxTrend=Math.max(1,...(report?.trend.map(x=>x.players)||[])),maxStage=Math.max(1,...(report?.stages.map(x=>x.plays)||[]));
 return <div className={styles.root}><header className={styles.header}><Link href="/" className={styles.brand}>ROCKETJUMP <span>ADMIN</span></Link><nav><a href="/drifter" target="_blank" rel="noopener">Open game ↗</a>{access?.signedIn&&<button onClick={logout}>Sign out</button>}</nav></header>
 {!access?.admin?<section className={styles.login}><span className={styles.eyebrow}>OWNER WORKSPACE</span><h1>Know how<br/>Drifter is doing.</h1><p>Live activity, world performance and the voices of your players.</p>{error&&<p className={styles.error} role="alert">{error}</p>}{!access?<p>Checking access…</p>:!access.signedIn?<form onSubmit={authenticate}><h2>{register?'Create your owner account':'Sign in to RocketJump'}</h2><label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" minLength={10} maxLength={128} autoComplete={register?'new-password':'current-password'} required/></label><button className={styles.primary} disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'}</button><button type="button" onClick={()=>setRegister(!register)}>{register?'Already have a game account? Sign in':'First visit? Create an account'}</button><small>Use your game account. Creating an account does not grant admin access.</small></form>:access.setupAvailable?<form onSubmit={claim}><h2>Activate owner access</h2><p>Enter the private setup code supplied with your owner invitation.</p><label>Owner setup code<input name="token" type="password" autoComplete="off" required/></label><button className={styles.primary} disabled={busy}>Activate dashboard</button></form>:<div className={styles.panel}><h2>Owner access required</h2><p>This account does not have access to player insights. Sign in with your authorised owner account.</p></div>}</section>:<main className={styles.main}>
 <div className={styles.heading}><div><span className={styles.eyebrow}>DRIFTER / GAME INSIGHTS</span><h1>Launch control.</h1><p>{report?'Updated '+new Date(report.generatedAt).toLocaleTimeString('en-ZA')+' · refreshes every minute':'Loading observed gameplay…'}</p></div><div className={styles.period} aria-label="Reporting period">{[1,7,30].map(d=><button key={d} aria-pressed={days===d} onClick={()=>setDays(d)}>{d===1?'24 hours':d+' days'}</button>)}<button onClick={()=>setRefresh(n=>n+1)} aria-label="Refresh insights">↻</button></div></div>
 {error&&<p className={styles.error} role="alert">{error} {report?'The figures below are from the last successful update.':''}</p>}
 {report&&<><div className={styles.metrics}><article><span><i className={styles.live}/> PLAYING NOW</span><strong>{number(report.active)}</strong><small>Active in the last 60 seconds</small></article>{report.windows.map(w=><article key={w.days}><span>{w.days===1?'LAST 24 HOURS':'LAST '+w.days+' DAYS'}</span><strong>{number(w.players)}</strong><small>Unique opted-in browsers</small></article>)}</div>
 <p className={styles.coverage}>{report.trackingSince?'Collection started '+new Date(report.trackingSince).toLocaleDateString('en-ZA')+'. Earlier activity is not available.':'No gameplay data yet. Figures will appear when players opt in and explore a planet.'}</p>
 <section className={styles.insights} aria-label="Game insights">{report.insights.map((i,n)=><article key={n} data-tone={i.tone}><span>{i.tone==='attention'?'LOOK CLOSER':i.tone==='positive'?'A USEFUL SIGNAL':'CONTEXT'}</span><h2>{i.title}</h2><p>{i.text}</p></article>)}</section>
 <div className={styles.columns}><section className={styles.panel}><div className={styles.panelHeading}><h2>Players over time</h2><span>Daily · UTC</span></div>{report.trend.length?<><div className={styles.chart} role="img" aria-label="Daily unique players: see the values below">{report.trend.map(t=><div key={t.day} title={new Date(t.day).toISOString().slice(0,10)+': '+t.players+' players'}><b>{t.players}</b><i style={{height:Math.max(3,t.players/maxTrend*160)}}/><small>{new Date(t.day).toLocaleDateString('en-ZA',{day:'numeric',month:'short',timeZone:'UTC'})}</small></div>)}</div></>:<p>No daily activity has been recorded.</p>}<div className={styles.summary}><span><b>{number(report.attempts)}</b> planet starts</span><span><b>{number(report.completions)}</b> completed</span><span><b>{number(report.activeMinutes)}</b> active minutes</span></div></section>
 <section className={styles.panel}><div className={styles.panelHeading}><h2>Most-played stages</h2><span>Stage entries</span></div>{report.stages.length?<ol className={styles.stages}>{report.stages.slice(0,8).map(s=><li key={s.planet+s.stage}><div><strong>{s.stageName}</strong><span>{s.name} · stage {s.stage+1}</span></div><b>{number(s.plays)} <small>plays · {s.players} browsers</small></b><i style={{width:(s.plays/maxStage*100)+'%'}}/></li>)}</ol>:<p>Stage rankings appear after players reach a world.</p>}</section></div>
 <section className={styles.panel}><div className={styles.panelHeading}><h2>Every world, at a glance</h2><span>Attempts started in this period</span></div><div className={styles.tableWrap}><table><thead><tr><th>Planet</th><th>Starts</th><th>Completed</th><th>Completion</th><th>Deaths</th><th>Exits / inactive</th></tr></thead><tbody>{report.planets.map(p=><tr key={p.planet}><th>{p.name}</th><td>{p.starts}</td><td>{p.completions}</td><td>{p.starts?Math.round(p.completions/p.starts*100):0}%</td><td>{p.deaths}</td><td>{p.exits}</td></tr>)}</tbody></table></div>{!report.planets.length&&<p>No planet attempts recorded yet.</p>}</section>
 <div className={styles.columns}><section className={styles.panel}><div className={styles.panelHeading}><h2>What players say</h2><span>Optional planet ratings</span></div>{report.feedback.length?<ul className={styles.feedback}>{report.feedback.map((f,i)=><li key={i}><b data-rating={f.rating}>{f.rating>0?'♡ Liked it':'Needs work'}</b><span>{f.name}<small>{f.reason}</small></span><strong>{f.votes}</strong></li>)}</ul>:<p>No ratings yet. Players can rate a planet after finishing or losing an attempt.</p>}</section><section className={styles.panel}><div className={styles.panelHeading}><h2>Technical health</h2><span>Client-reported errors</span></div>{report.errors.length?<ul className={styles.feedback}>{report.errors.map((e,i)=><li key={i}><span>{e.name}<small>{e.value||'runtime'}</small></span><strong>{e.reports}</strong></li>)}</ul>:<p>No gameplay error reports in this period. This is not a guarantee that every device is bug-free.</p>}</section></div>
 <details className={styles.definitions}><summary>How these numbers are measured</summary>{Object.entries(report.definitions).map(([key,text])=><p key={key}><strong>{key}: </strong>{text}</p>)}<p>Raw gameplay activity is retained for 35 days. Satisfaction ratings are self-selected. No historical figures are invented or imported from test runs.</p></details>
 </>}
 </main>}<footer className={styles.footer}>ROCKETJUMP · Private owner workspace <Link href="/privacy">Privacy</Link></footer></div>;
}
