import type { Metadata } from "next";
import Link from "next/link";
import { CTASection, FeatureList, PageHero, SectionHeading } from "@/components/UI";
import { maintenancePackages, pageMetadata, websitePackages } from "@/lib/site";

export const metadata: Metadata = pageMetadata("Web Design & Website Packages", "Modern website design in Gqeberha, from focused launch pages to custom platforms and eCommerce.", "/web-design");

export default function WebDesignPage() {
  const included = ["Responsive, mobile-first design", "SSL security", "Basic SEO foundation", "Performance optimisation", "Social media integration", "Contact functionality", "Modern development technology", "Domain connection", "Local support", "Clear calls to action", "Accessibility-conscious development"];
  return <>
    <PageHero eyebrow="WEB DESIGN" title="Modern websites built to perform." copy="RocketJump designs high-performance websites that look exceptional, work beautifully across every screen and make it easy for customers to take action." accent="pink" visual="web"/>
    <section className="section-light packages"><div className="shell"><SectionHeading eyebrow="WEBSITE PACKAGES" title="A clear place to start." copy="Choose a package, tell us about your business and let us handle the rest."/><div className="package-grid">{websitePackages.map((pkg) => <article className={`package-card ${pkg.popular ? "popular" : ""}`} key={pkg.name}>{pkg.popular && <span className="popular-label">MOST POPULAR</span>}<h3>{pkg.name}</h3><strong>{pkg.price}</strong><p>{pkg.summary}</p><FeatureList items={pkg.features}/><Link href={`/contact?package=${encodeURIComponent(pkg.name)}`} className="button">{pkg.cta} <span>↗</span></Link><small>Final price depends on content, features and project requirements.</small></article>)}</div></div></section>
    <section className="ecommerce"><div className="shell split-section"><div><SectionHeading eyebrow="ECOMMERCE" title="Sell online with confidence." copy="Custom eCommerce solutions for businesses that need a dependable, mobile-friendly way to sell products or services online."/><strong className="large-price">From R14,999</strong><div className="commerce-ownership"><span>OWN YOUR STORE</span><h3>No Shopify subscription. No store-builder lock-in.</h3><p>We build your own eCommerce platform around your business, running on a managed backend so you stay in control of your store, customer information and future growth.</p></div><p className="small-print">There is no recurring Shopify or store-builder platform subscription. Direct costs such as hosting, payment processing, domains and any chosen integrations are quoted clearly for your setup.</p><Link href="/contact?package=eCommerce%20Website" className="button">Choose eCommerce <span>↗</span></Link></div><FeatureList columns={2} items={["Your own custom eCommerce platform", "No Shopify or store-builder subscription", "Secure payment integration", "Shopping cart and customer accounts", "Order and stock management", "Shipping and collection options", "Discount codes", "Sales analytics"]}/></div></section>
    <section className="section-light website-portal"><div className="shell split-section"><div><SectionHeading eyebrow="ROCKETJUMP CLIENT PORTAL" title="You stay in control of your website." copy="Your project, approvals and essential website information live in one clear place. See what is moving forward, review designs, request updates and keep the important information accessible."/><Link href="/client-portal" className="button">Explore the client portal <span>↗</span></Link></div><FeatureList columns={2} items={["See project progress and next steps", "Review and approve designs", "Request website updates in one place", "Access key website information", "Keep feedback clear and traceable", "Stay connected without long email threads"]}/></div></section>
    <section className="section-light included"><div className="shell split-section"><SectionHeading eyebrow="EVERY WEBSITE INCLUDES" title="The essentials are never optional." copy="A strong technical foundation is built into every RocketJump website."/><FeatureList items={included} columns={2}/></div></section>
    <section className="hosting"><div className="shell split-section"><div><SectionHeading eyebrow="WEBSITE HOSTING" title="Fast, secure website hosting." copy="Reliable cloud infrastructure, global content delivery and technical support without the jargon."/><strong className="large-price">From R99/month</strong><p className="small-print">Pricing may vary for high-traffic websites, web applications, database usage or advanced infrastructure.</p></div><FeatureList items={["Fast global content delivery", "Automatic SSL security", "Reliable cloud infrastructure", "High availability", "Performance monitoring", "Protection against common web threats", "Seamless scaling", "Domain connection and technical support"]}/></div></section>
    <section className="section-light maintenance"><div className="shell"><SectionHeading eyebrow="WEBSITE MAINTENANCE" title="Affordable care after launch." copy="Hosting keeps your website online. Maintenance keeps it current, monitored and supported."/><div className="maintenance-grid">{maintenancePackages.map((pkg) => <article key={pkg.name}><h3>{pkg.name}</h3><strong>{pkg.price}</strong><FeatureList items={pkg.features}/><Link href="/contact" className="text-link">Ask about this plan <span>↗</span></Link></article>)}</div><p className="fine-print">Unused maintenance time does not roll over unless explicitly agreed. Work outside the monthly allocation is quoted or billed separately.</p></div></section>
    <section className="content-email"><div className="shell promo-grid"><article><span className="eyebrow">CONTENT MANAGEMENT</span><h2>Want to update your own content?</h2><p>We can add a secure dashboard so approved users can update selected text, images, services, team members, articles, projects and SEO descriptions without touching the design or code.</p><Link href="/contact" className="button">Ask About a Client-Editable Website <span>↗</span></Link><small>Setup is priced separately according to editable sections, users and workflows.</small></article><article><span className="eyebrow">PROFESSIONAL EMAIL</span><h2>Email that looks like your business.</h2><p>We can help configure branded addresses such as <code>hello@yourbusiness.co.za</code>, with cloud access, spam protection, forwarding, calendars and shared inboxes where needed.</p><Link href="/contact" className="button button-purple">Ask About Professional Email <span>↗</span></Link></article></div></section>
    <CTASection title="Ready for a website that works harder?"/>
  </>;
}
